version: "3.2"
services:
  jupyter:
    container_name: "ml"
    build:
      context: "./Dockerfiles"
      dockerfile: "Dockerfile-jupyter"
    ports:
      - "8888:8888"
    volumes:
      - type: "bind"
        source: "./ateliers"
        target: "/opt/notebook"
