FROM continuumio/anaconda3

ENV TINI_VERSION v0.17.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN /opt/conda/bin/conda update -n base conda && \
	/opt/conda/bin/conda install jupyter -y --quiet && \
	mkdir /opt/notebook && \
	chmod +x /usr/bin/tini

EXPOSE 8888

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/opt/conda/bin/jupyter", "notebook", "--notebook-dir=/opt/notebook", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]
